import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="facebook-domain-verification"
        content="k073pkts9wd9oj3s043j1yqiucjmwx"
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
